### ISSUE TITLE
Error encountered during testing script execution

### ISSUE THREAD

**Issue by BaptFontaine** [oneformer3d/oneformer3d#39]
I am encountering an error when attempting to run the testing script after successfully training the model on the S3DIS dataset. The error message I'm receiving is as follows:
Traceback (most recent call last):
  File "tools/test.py", line 149, in <module>
    main()
  File "tools/test.py", line 145, in main
    runner.test()
  File "/home/baptiste/miniconda3/envs/OF3D/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1823, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/baptiste/miniconda3/envs/OF3D/lib/python3.8/site-packages/mmengine/runner/loops.py", line 443, in run
    self.run_iter(idx, data_batch)
  File "/home/baptiste/miniconda3/envs/OF3D/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/baptiste/miniconda3/envs/OF3D/lib/python3.8/site-packages/mmengine/runner/loops.py", line 464, in run_iter
    self.runner.call_hook(
  File "/home/baptiste/miniconda3/envs/OF3D/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1841, in call_hook
    raise TypeError(f'{e} in {hook}') from None
TypeError: add_datasample() got an unexpected keyword argument 'vis_task' in <mmdet3d.engine.hooks.visualization_hook.Det3DVisualizationHook object at 0x7fa091151640>

This error occurs when executing the testing script with the following command:
python tools/test.py configs/oneformer3d_1xb2_s3dis-area-5.py work_dirs/oneformer3d_1xb2_s3dis-area-5/epoch_512.pth --show-dir results/oneformer3d_1xb2_s3dis-area-5 --task lidar_det

I seek assistance in either resolving this error or finding an alternative method to save the results generated by the testing script. Any guidance or suggestions would be appreciated.

**Comment by oneformer3d-contributor** [comment]
Yes, these code is not ready from mmdetecion3d visualization, mainly because we predict three types of segmentation masks simultaniously. You can simply save the input and the output from [predict](https://github.com/oneformer3d/oneformer3d/blob/main/oneformer3d/oneformer3d.py#L784) function and then visualize them.

**Comment by jiachen0212** [comment]
> Yes, these code is not ready from mmdetecion3d visualization, mainly because we predict three types of segmentation masks simultaniously. You can simply save the input and the output from [predict](https://github.com/oneformer3d/oneformer3d/blob/main/oneformer3d/oneformer3d.py#L784) function and then visualize them.

will the code add mmdetecion3d visualization?  we also need to predict the orientation of 3D objects~

**Comment by oneformer3d-contributor** [comment]
Unfortunately no plans for adding object detection or visualization to this repo.
