### ISSUE TITLE
Can I Skip Training on Structured3D and ScanNet for S3DIS Instance Segmentation?

### ISSUE THREAD

**Issue by Saltarello2023** [oneformer3d/oneformer3d#54]
Thanks for your excellent job! Is it possible to focus solely on the S3DIS dataset for instance segmentation tasks without training on the Structured3D and ScanNet datasets? They're just so massive.

**Comment by oneformer3d-contributor** [comment]
Hi @Saltarello2023 ,
I think we point out in the readme that you can download scannet + structured3d pretrained model and start training on s3dis with it.

**Comment by Saltarello2023** [comment]
> Hi @Saltarello2023 , 你好 I think we point out in the readme that you can download scannet + structured3d pretrained model and start training on s3dis with it.我认为我们在自述文件中指出，您可以下载scannet + structured3d预训练模型，并用它开始在s3dis上进行训练。

Sorry to bother you again, but when I try to run the command 'python tools/train.py configs/oneformer3d_1xb2_s3dis-area-5.py' directly, it fails. The error message is as follows:

Traceback (most recent call last):
  File "/workspace/tools/train.py", line 135, in <module>
    main()
  File "/workspace/tools/train.py", line 131, in main
    runner.train()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1520, in build_train_loop
    loop = LOOPS.build(
  File "/opt/conda/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/dataset/dataset_wrapper.py", line 47, in __init__
    self.datasets.append(DATASETS.build(dataset))
  File "/opt/conda/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmdet3d/datasets/s3dis_dataset.py", line 86, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.10/site-packages/mmdet3d/datasets/det3d_dataset.py", line 126, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 298, in full_init
    self.data_list = self.load_data_list()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 435, in load_data_list
    annotations = load(self.ann_file)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/fileio/io.py", line 855, in load
    with BytesIO(file_backend.get(file)) as f:
  File "/opt/conda/lib/python3.10/site-packages/mmengine/fileio/backends/local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/s3dis/s3dis_infos_Area_1.pkl'

Could you give me some guidance, as I'm not very familiar with your code, but I'd be immensely grateful either way.

**Comment by oneformer3d-contributor** [comment]
Did you generate .pkl annotation files for S3DIS with mmdetection3d [script](https://github.com/open-mmlab/mmdetection3d/tree/22aaa47fdb53ce1870ff92cb7e3f96ae38d17f61/data/s3dis)?

**Comment by Saltarello2023** [comment]
> Did you generate .pkl annotation files for S3DIS with mmdetection3d [script](https://github.com/open-mmlab/mmdetection3d/tree/22aaa47fdb53ce1870ff92cb7e3f96ae38d17f61/data/s3dis)?您是否使用 mmdetection3d 脚本为 S3DIS 生成了 .pkl 注释文件？

Thank you for your guidance. I have successfully completed this part, but my GPU memory is only 4GB, so I can't run this code. It gives an error saying "CUDA out of memory," and setting batch_size=1 doesn't work either. Is there any way to modify some parameters to train it? My gpu is a 3050 Ti.

**Comment by oneformer3d-contributor** [comment]
Unfortunately, training with 4 Gb is impossible for OneFormer3D, it should be several times more.

**Comment by Saltarello2023** [comment]
> Unfortunately, training with 4 Gb is impossible for OneFormer3D, it should be several times more.

Could you please tell me the minimum graphics card memory requirement for training on the S3DIS dataset?Thanks！

**Comment by oneformer3d-contributor** [comment]
Actually it is 32 Gb, but can be reduced to 24 Gb, i think. Please try #24 and #11.

**Comment by Serissa** [comment]
> > Unfortunately, training with 4 Gb is impossible for OneFormer3D, it should be several times more.
> 
> Could you please tell me the minimum graphics card memory requirement for training on the S3DIS dataset?Thanks！

Hello! How do you use the s2dis data to handle the data format that can be used for training?

**Comment by oneformer3d-contributor** [comment]
What do you mean by `scannet_frames_25k`? I think we don't use it, we use only point clouds.

**Comment by 242726Yuncheng** [comment]
> What do you mean by `scannet_frames_25k`? I think we don't use it, we use only point clouds.
It`s a sub-dataset, the file structure is shown in the following figure. I would like to know what to do with the data, I don't really understand the readme you provided
![微信图片_20240609221944](https://github.com/oneformer3d/oneformer3d/assets/105715240/effd2f98-fa8b-496f-8dff-53352061c890)

**Comment by oneformer3d-contributor** [comment]
So, using this data ScanNet auhors first reconstruct a single mesh per room, that sample a point cloud from it, and then OneFormer3D comes to take this point cloud as as input. We don't operate directly with depth and color images.
